AWSTemplateFormatVersion: 2010-09-09
Description: Neptune full stack with gremlin and rd4j console
Parameters:
  CloudFormationS3Path:
    Description: Path to the folder that the cf-base and cf-ec2 files reside. Required.
    Type: String
    Default: ''
  EC2SSHKeyPairName:
    Description: >-
      Name of an existing EC2 KeyPair to enable SSH access to the instances.
      Required Input
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair in same region.
  Env:
    Description: 'Environment tag, e.g. prod, nonprod.'
    Default: test
    Type: String
    AllowedPattern: '[a-z0-9]+'
    MaxLength: 15
  DbInstanceType:
    Description: Neptune DB instance type
    Type: String
    Default: db.r4.xlarge
    AllowedValues:
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
    ConstraintDescription: >-
      Must be a valid Neptune instance type. Note that for Stockholm only R5
      instances are available.
  DBReplicaIdentifierSuffix:
    Description: >-
      OPTIONAL: The ID for the Neptune Replica to use. Empty means no read
      replica.
    Type: String
    Default: ''
  DBClusterPort:
    Type: String
    Default: '8182'
    Description: Enter the port of your Neptune cluster
  EC2ClientInstanceType:
    Description: EC2 client instance
    Type: String
    Default: r4.2xlarge
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.12xlarge
    ConstraintDescription: >-
      Must be a valid EC2 instance type. Note some regions support limited
      instance types only. Ex: Stockholm do not support R4 instances
  NeptuneQueryTimeout:
    Type: Number
    Default: 20000
    Description: Neptune Query Time out (in milliseconds)
  NeptuneEnableAuditLog:
    Type: Number
    Default: 0
    AllowedValues:
      - 0
      - 1
    Description: Enable Audit Log. 0 means disable and 1 means enable.
  IamAuthEnabled:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable IAM Auth for Neptune.
  SetupGremlinConsole:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Setup Gremlin console.
  SetupRDF4JConsole:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Setup RDF4J console.
  AttachBulkloadIAMRoleToNeptuneCluster:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Attach Bulkload IAM role to cluster
Rules:
  DBInstanceTypeVsRegion:
    RuleCondition: !Equals 
      - !Ref 'AWS::Region'
      - eu-north-1
    Assertions:
      - Assert:
          'Fn::Contains':
            - - db.r5.large
              - db.r5.xlarge
              - db.r5.2xlarge
              - db.r5.4xlarge
              - db.r5.12xlarge
            - !Ref DbInstanceType
        AssertDescription: Only R5 Instances are available in eu-north-1 (Stockholm).
  EC2ClientInstanceTypeVsRegion:
    RuleCondition: !Equals 
      - !Ref 'AWS::Region'
      - eu-north-1
    Assertions:
      - Assert: !Not 
          - 'Fn::Contains':
              - - r4.large
                - r4.xlarge
                - r4.2xlarge
                - r4.4xlarge
                - r4.8xlarge
              - !Ref EC2ClientInstanceType
        AssertDescription: R4 Instances are not available in eu-north-1 (Stockholm).
Conditions:
  CreateDBReplicaInstance: !Not 
    - !Equals 
      - !Ref DBReplicaIdentifierSuffix
      - ''
  AZ3Present: !Not 
    - !Equals 
      - !Ref 'AWS::Region'
      - ap-northeast-2
Resources:
  NeptuneStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub ${CloudFormationS3Path}cf-base.yaml
      TimeoutInMinutes: '15'
      Parameters:
        Env: !Ref Env
        DBReplicaIdentifierSuffix: !Ref DBReplicaIdentifierSuffix
        DBClusterPort: !Ref DBClusterPort
        DbInstanceType: !Ref DbInstanceType
        NeptuneQueryTimeout: !Ref NeptuneQueryTimeout
        NeptuneEnableAuditLog: !Ref NeptuneEnableAuditLog
        IamAuthEnabled: !Ref IamAuthEnabled
  NeptuneEC2Client:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub ${CloudFormationS3Path}cf-ec2.yaml
      TimeoutInMinutes: '30'
      Parameters:
        Env: !Ref Env
        EC2SSHKeyPairName: !Ref EC2SSHKeyPairName
        EC2ClientInstanceType: !Ref EC2ClientInstanceType
        SetupGremlinConsole: !Ref SetupGremlinConsole
        SetupRDF4JConsole: !Ref SetupRDF4JConsole
        AttachBulkloadIAMRoleToNeptuneCluster: !Ref AttachBulkloadIAMRoleToNeptuneCluster
        VPC: !GetAtt 
          - NeptuneStack
          - Outputs.VPC
        Subnet: !GetAtt 
          - NeptuneStack
          - Outputs.PublicSubnet1
        NeptuneDBCluster: !GetAtt 
          - NeptuneStack
          - Outputs.DBClusterId
        NeptuneDBClusterEndpoint: !GetAtt 
          - NeptuneStack
          - Outputs.DBClusterEndpoint
        NeptuneDBClusterPort: !GetAtt 
          - NeptuneStack
          - Outputs.DBClusterPort
        NeptuneLoadFromS3IAMRoleArn: !GetAtt 
          - NeptuneStack
          - Outputs.NeptuneLoadFromS3IAMRoleArn
        NeptuneSG: !GetAtt 
          - NeptuneStack
          - Outputs.NeptuneSG
        NeptuneClientSG: !GetAtt 
          - NeptuneStack
          - Outputs.NeptuneClientSG
        NeptuneEC2InstanceProfile: !GetAtt 
          - NeptuneStack
          - Outputs.NeptuneEC2InstanceProfile
  NeptuneLambda:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub ${CloudFormationS3Path}cf-lambda.yaml
      Parameters:
        LambdaRuntime: python3.6
        NeptuneSGs: !GetAtt
          - NeptuneStack
          - Outputs.NeptuneClientSG
        Subnets: !GetAtt 
          - NeptuneStack
          - Outputs.PublicSubnet1
          - !GetAtt 
          - NeptuneStack
          - Outputs.PublicSubnet2
          - !GetAtt 
          - NeptuneStack
          - Outputs.PublicSubnet3
        NeptuneClusterEndpoint: !GetAtt 
          - NeptuneStack
          - Outputs.DBClusterEndpoint
        NeptuneClusterPort: !GettAtt
          - NeptuneStack
          - Outputs.DBClusterPort
Outputs:
  DBClusterId:
    Description: Neptune Cluster Identifier
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBClusterId
  DBSubnetGroupId:
    Description: Neptune DBSubnetGroup Identifier
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBSubnetGroupId
  DBClusterResourceId:
    Description: Neptune Cluster Resource Identifier
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBClusterResourceId
  DBClusterEndpoint:
    Description: Master Endpoint for Neptune Cluster
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBClusterEndpoint
  DBInstanceEndpoint:
    Description: Master Instance Endpoint
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBInstanceEndpoint
  DBReplicaInstanceEndpoint:
    Description: ReadReplica Instance Endpoint
    Condition: CreateDBReplicaInstance
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBReplicaInstanceEndpoint
  SparqlEndpoint:
    Description: Sparql Endpoint for Neptune
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.SparqlEndpoint
  GremlinEndpoint:
    Description: Gremlin Endpoint for Neptune
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.GremlinEndpoint
  LoaderEndpoint:
    Description: Loader Endpoint for Neptune
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.LoaderEndpoint
  DBClusterReadEndpoint:
    Description: DB cluster Read Endpoint
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBClusterReadEndpoint
  DBClusterPort:
    Description: Port for the Neptune Cluster
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.DBClusterPort
  NeptuneLoadFromS3IAMRoleArn:
    Description: IAM Role for loading data in Neptune
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.NeptuneLoadFromS3IAMRoleArn
  NeptuneIamAuthUser:
    Description: IAM User for IAM Auth
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.NeptuneIamAuthUser
  EC2Client:
    Description: EC2 client Identifier
    Value: !GetAtt 
      - NeptuneEC2Client
      - Outputs.EC2Client
  SSHAccess:
    Description: This is how you gain remote access to the EC2 client.
    Value: !GetAtt 
      - NeptuneEC2Client
      - Outputs.SSHAccess
  VPC:
    Description: VPC
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.VPC
  Subnet1:
    Description: Subnet1
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.PublicSubnet1
  Subnet2:
    Description: Subnet2
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.PublicSubnet2
  Subnet3:
    Description: Subnet3
    Condition: AZ3Present
    Value: !GetAtt 
      - NeptuneStack
      - Outputs.PublicSubnet3
